// Generated by tools/bake_constants.py from tools/cave.py.
// Do not edit: change cave.py and re-run the baker.
#pragma once
#include <stdint.h>
#include "labels.h"

// ---- pacing -----------------------------------------------------
// Every rate is per SECOND. Distance is measured in cave columns.
// Frame-rate independence is verified in the Python model across
// 30-144 fps; keep it that way -- per-frame rates put the sun at 25 s
// on a 50 fps device and 14 s on a 90 fps one.
constexpr float SPEED_START    = 55.0f;   // columns/second at distance 0
constexpr float SPEED_END      = 100.0f;  // columns/second once ramped
constexpr float SPEED_RAMP_END = 16000.0f;
constexpr float GAP_START      = 0.480f;  // fraction of panel height
constexpr float GAP_MIN        = 0.210f;
constexpr float GAP_RAMP_END   = 12000.0f;

// ---- the return -------------------------------------------------
// Republic ~516e-517a. Both ascent levers are spent by the sun --
// the gap floors at GAP_RAMP_END, the speed caps at SPEED_RAMP_END --
// so the descent uncaps them rather than repeating the climb.
constexpr float SUN_HOLD       = 3000.0f;   // distance held at the sun before turning back
constexpr float DESCENT_START  = 19000.0f;
constexpr float SPEED_DESC_END = 145.0f;  // columns/second at the chains
constexpr float GAP_DESC_MIN   = 0.150f;  // fraction of H
constexpr float WIN_DIST       = 33000.0f;   // reaching this completes the game

// The closing view: the returning eye cannot see far. Applied AFTER
// the rock edge is drawn, so the edge is occluded too -- otherwise
// the passage ahead stays readable and the mechanic does nothing.
// TUNING RISK: at VIEW_CLOSE 0.55 the clear view at the chains is
// ~0.60s against 3.62s at the start. 0.40 gives ~0.82s. Unresolved
// until played.
constexpr float VIEW_CLOSE = 0.55f;   // fraction of width swallowed
constexpr float VIEW_DEPTH = 0.92f;   // dimming at the right edge

// ---- trail ------------------------------------------------------
// Two constraints the firmware must honour or the trail vanishes:
//
//  1. Draw it as CONNECTED SEGMENTS, not isolated points. A single
//     pixel cannot compete with a single-pixel dither -- in a
//     50-80% lit field it is just another dither cell.
//  2. Flip its polarity on the region's light. Brighter than the
//     passage below 128/255, darker above; a trail that only
//     brightens is invisible from SELENE onward.
//
// TWIN_TRAIL draws two strands rather than one: the Phaedrus
// chariot's two horses, whichever is being obeyed leading. Set 0
// for a single strand.
constexpr uint8_t TWIN_TRAIL   = 1;
constexpr float   TRAIL_BASE   = 1.40f;  // px of divergence at the player
constexpr float   TRAIL_SPREAD = 0.10f;  // px added per frame of age
constexpr uint8_t TRAIL_LEN    = 40;      // points retained

// ---- region texture ---------------------------------------------
// Three regions name something that behaves, not just something
// coloured. Matched on Region::label, so the return gets them too.
constexpr uint8_t FLICKER_LABEL = LBL_PYR;   // firelight is not steady
constexpr float   FLICKER_DEPTH = 0.16f;  // peak swing in light
constexpr uint8_t STARS_LABEL   = LBL_ASTRA;   // rock reads as sky by now
constexpr uint16_t STAR_RARITY  = 1400;    // 1 in N rock pixels
// Stars are placed by WORLD column, not screen column, or they
// swim across the rock as the cave scrolls.

// HYDOR has no special texture. A reflection was built and
// rejected; see GAME_DESIGN.

// ---- physics ----------------------------------------------------
// Scaled by panel height H. THRUST replaces gravity while the
// button is held; it does not add to it.
// UNVALIDATED: these three have never been driven by a human thumb.
constexpr float GRAVITY = 5.00f;   // * H px/s^2
constexpr float THRUST  = -7.50f;   // * H px/s^2
constexpr float VY_MAX  = 1.00f;   // * H px/s

// ---- cave shape -------------------------------------------------
constexpr float DRIFT_STEP   = 0.42f;   // uniform +/- per column
constexpr float DRIFT_CLAMP  = 2.60f;
constexpr float DRIFT_DAMP   = 0.94f;
constexpr float WALL_MARGIN  = 0.06f;   // * H, beyond gap/2
constexpr float PLAYER_X_FRAC = 0.17f;  // * W

// ---- regions ----------------------------------------------------
// Republic 514a-517a ascending, then the return. Each region names
// its own light source, which is where its colour comes from. The
// return reuses the ascent's names and colours at lower light: the
// prisoner coming back from the sun cannot see in the dark.
struct Region {
  uint8_t  label;    // index into LABELS[] in labels.h
  uint32_t from;     // distance at which this region begins
  uint8_t  light;    // dither density, 0-255
  uint16_t rock;     // RGB565
  uint16_t glow;     // RGB565
};

constexpr uint8_t REGION_COUNT = 13;
constexpr uint8_t ASCENT_COUNT = 7;   // regions at and past this index are the return
inline constexpr Region REGIONS[REGION_COUNT] = {
  {LBL_SKIAI,               0,  36, 0x0021, 0x4ACD},  //  0 ΣΚΙΑΙ    ascent
  {LBL_PYR,               700,  61, 0x0820, 0xEBA4},  //  1 ΠΥΡ      ascent
  {LBL_EIDOLA,           1800,  92, 0x1040, 0xFDA9},  //  2 ΕΙΔΩΛΑ   ascent
  {LBL_HYDOR,            3400, 128, 0x0062, 0x563B},  //  3 ΥΔΩΡ     ascent
  {LBL_ASTRA,            6000, 163, 0x0022, 0x9CBE},  //  4 ΑΣΤΡΑ    ascent
  {LBL_SELENE,           9900, 204, 0x0862, 0xCF1F},  //  5 ΣΕΛΗΝΗ   ascent
  {LBL_HELIOS,          16000, 255, 0x1060, 0xFFBA},  //  6 ΗΛΙΟΣ    ascent
  {LBL_SELENE,          19000, 147, 0x0862, 0xCF1F},  //  7 ΣΕΛΗΝΗ   return
  {LBL_ASTRA,           22200, 108, 0x0022, 0x9CBE},  //  8 ΑΣΤΡΑ    return
  {LBL_HYDOR,           25000,  76, 0x0062, 0x563B},  //  9 ΥΔΩΡ     return
  {LBL_EIDOLA,          27400,  50, 0x1040, 0xFDA9},  // 10 ΕΙΔΩΛΑ   return
  {LBL_PYR,             29500,  29, 0x0820, 0xEBA4},  // 11 ΠΥΡ      return
  {LBL_SKIAI,           31300,  15, 0x0021, 0x4ACD},  // 12 ΣΚΙΑΙ    return
};

// ---- dither -----------------------------------------------------
// 8x8 Bayer, scaled to 0-255 so it compares directly against
// Stage::light with no division at draw time.
inline constexpr uint8_t BAYER8[64] = {
    0, 128,  32, 159,   8, 135,  40, 167,
  191,  64, 223,  96, 199,  72, 231, 104,
   48, 175,  16, 143,  56, 183,  24, 151,
  239, 112, 207,  80, 247, 120, 215,  88,
   12, 139,  44, 171,   4, 131,  36, 163,
  203,  76, 235, 108, 195,  68, 227, 100,
   60, 187,  28, 155,  52, 179,  20, 147,
  251, 124, 219,  92, 243, 116, 211,  84,
};
