// Generated by tools/bake_constants.py from tools/cave.py.
// Do not edit: change cave.py and re-run the baker.
#pragma once
#include <stdint.h>
#include "labels.h"

// ---- pacing -----------------------------------------------------
// Every rate is per SECOND. Distance is measured in cave columns.
// Frame-rate independence is verified in the Python model across
// 30-144 fps; keep it that way -- per-frame rates put the sun at 25 s
// on a 50 fps device and 14 s on a 90 fps one.
constexpr float SPEED_START    = 55.0f;   // columns/second at distance 0
constexpr float SPEED_END      = 100.0f;  // columns/second once ramped
constexpr float SPEED_RAMP_END = 16000.0f;
constexpr float GAP_START      = 0.480f;  // fraction of panel height
constexpr float GAP_MIN        = 0.210f;
constexpr float GAP_RAMP_END   = 12000.0f;

// ---- physics ----------------------------------------------------
// Scaled by panel height H. THRUST replaces gravity while the
// button is held; it does not add to it.
// UNVALIDATED: these three have never been driven by a human thumb.
constexpr float GRAVITY = 7.80f;   // * H px/s^2
constexpr float THRUST  = -9.60f;   // * H px/s^2
constexpr float VY_MAX  = 1.26f;   // * H px/s

// ---- cave shape -------------------------------------------------
constexpr float DRIFT_STEP   = 0.42f;   // uniform +/- per column
constexpr float DRIFT_CLAMP  = 2.60f;
constexpr float DRIFT_DAMP   = 0.94f;
constexpr float WALL_MARGIN  = 0.06f;   // * H, beyond gap/2
constexpr float PLAYER_X_FRAC = 0.17f;  // * W

// ---- stages -----------------------------------------------------
// Republic 514a-517a, in order. Each stage names its own light
// source, which is where its colour comes from.
struct Stage {
  uint8_t  label;    // index into LABELS[] in labels.h
  uint32_t from;     // distance at which this stage begins
  uint8_t  light;    // dither density, 0-255
  uint16_t rock;     // RGB565
  uint16_t glow;     // RGB565
};

constexpr uint8_t STAGE_COUNT = 7;
inline constexpr Stage STAGES[STAGE_COUNT] = {
  {LBL_SKIAI               0,  36, 0x0021, 0x4ACD},  // ΣΚΙΑΙ
  {LBL_PYR               700,  61, 0x0820, 0xEBA4},  // ΠΥΡ
  {LBL_EIDOLA           1800,  92, 0x1040, 0xFDA9},  // ΕΙΔΩΛΑ
  {LBL_HYDOR            3400, 128, 0x0062, 0x563B},  // ΥΔΩΡ
  {LBL_ASTRA            6000, 163, 0x0022, 0x9CBE},  // ΑΣΤΡΑ
  {LBL_SELENE           9900, 204, 0x0862, 0xCF1F},  // ΣΕΛΗΝΗ
  {LBL_HELIOS          16000, 255, 0x1060, 0xFFBA},  // ΗΛΙΟΣ
};

// ---- dither -----------------------------------------------------
// 8x8 Bayer, scaled to 0-255 so it compares directly against
// Stage::light with no division at draw time.
inline constexpr uint8_t BAYER8[64] = {
    0, 128,  32, 159,   8, 135,  40, 167,
  191,  64, 223,  96, 199,  72, 231, 104,
   48, 175,  16, 143,  56, 183,  24, 151,
  239, 112, 207,  80, 247, 120, 215,  88,
   12, 139,  44, 171,   4, 131,  36, 163,
  203,  76, 235, 108, 195,  68, 227, 100,
   60, 187,  28, 155,  52, 179,  20, 147,
  251, 124, 219,  92, 243, 116, 211,  84,
};
