#!/usr/bin/env python3
"""
Export the game's tuning constants from cave.py as a C header.

    python bake_constants.py

Writes firmware/plato/assets/constants.h.

This exists because the same values once lived in both tools/preview.py and the
T-QT sketch, kept in step by a comment asking editors to remember -- and they
drifted within a day. cave.py is the single source of truth; the firmware reads
what this emits and nobody retypes anything.

Colours are converted to RGB565 here rather than on the device, since that is
what the ST7789 wants and the conversion is fixed.
"""

import argparse
from pathlib import Path

import cave
from bake_assets import LABELS

OUT = Path(__file__).parent.parent / "firmware" / "plato" / "assets"


def rgb565(rgb) -> int:
    r, g, b = rgb
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def label_index(greek: str) -> int:
    for i, (_, text) in enumerate(LABELS):
        if text == greek:
            return i
    raise SystemExit(f"stage '{greek}' has no baked label -- add it to "
                     f"LABELS in bake_assets.py")


def emit() -> str:
    p = ["// Generated by tools/bake_constants.py from tools/cave.py.\n"
         "// Do not edit: change cave.py and re-run the baker.\n"
         "#pragma once\n#include <stdint.h>\n#include \"labels.h\"\n\n"
         "// ---- pacing -----------------------------------------------------\n"
         "// Every rate is per SECOND. Distance is measured in cave columns.\n"
         "// Frame-rate independence is verified in the Python model across\n"
         "// 30-144 fps; keep it that way -- per-frame rates put the sun at 25 s\n"
         "// on a 50 fps device and 14 s on a 90 fps one.\n"]

    p.append(f"constexpr float SPEED_START    = {cave.SPEED_START:.1f}f;"
             "   // columns/second at distance 0\n")
    p.append(f"constexpr float SPEED_END      = {cave.SPEED_END:.1f}f;"
             "  // columns/second once ramped\n")
    p.append(f"constexpr float SPEED_RAMP_END = {cave.SPEED_RAMP_END}.0f;\n")
    p.append(f"constexpr float GAP_START      = {cave.GAP_START:.3f}f;"
             "  // fraction of panel height\n")
    p.append(f"constexpr float GAP_MIN        = {cave.GAP_MIN:.3f}f;\n")
    p.append(f"constexpr float GAP_RAMP_END   = {cave.GAP_RAMP_END}.0f;\n\n")

    p.append("// ---- physics ----------------------------------------------------\n"
             "// Scaled by panel height H. THRUST replaces gravity while the\n"
             "// button is held; it does not add to it.\n"
             "// UNVALIDATED: these three have never been driven by a human thumb.\n")
    p.append(f"constexpr float GRAVITY = {cave.GRAVITY:.2f}f;   // * H px/s^2\n")
    p.append(f"constexpr float THRUST  = {cave.THRUST:.2f}f;   // * H px/s^2\n")
    p.append(f"constexpr float VY_MAX  = {cave.VY_MAX:.2f}f;   // * H px/s\n\n")

    p.append("// ---- cave shape -------------------------------------------------\n"
             "constexpr float DRIFT_STEP   = 0.42f;   // uniform +/- per column\n"
             "constexpr float DRIFT_CLAMP  = 2.60f;\n"
             "constexpr float DRIFT_DAMP   = 0.94f;\n"
             "constexpr float WALL_MARGIN  = 0.06f;   // * H, beyond gap/2\n"
             "constexpr float PLAYER_X_FRAC = 0.17f;  // * W\n\n")

    p.append("// ---- stages -----------------------------------------------------\n"
             "// Republic 514a-517a, in order. Each stage names its own light\n"
             "// source, which is where its colour comes from.\n"
             "struct Stage {\n"
             "  uint8_t  label;    // index into LABELS[] in labels.h\n"
             "  uint32_t from;     // distance at which this stage begins\n"
             "  uint8_t  light;    // dither density, 0-255\n"
             "  uint16_t rock;     // RGB565\n"
             "  uint16_t glow;     // RGB565\n"
             "};\n\n")
    p.append(f"constexpr uint8_t STAGE_COUNT = {len(cave.STAGES)};\n")
    p.append("inline constexpr Stage STAGES[STAGE_COUNT] = {\n")
    for name, start, light, rock, glow in cave.STAGES:
        p.append(f"  {{LBL_{LABELS[label_index(name)][0]:<14}"
                 f" {start:>6}, {round(light * 255):>3},"
                 f" 0x{rgb565(rock):04X}, 0x{rgb565(glow):04X}}},"
                 f"  // {name}\n")
    p.append("};\n\n")

    p.append("// ---- dither -----------------------------------------------------\n"
             "// 8x8 Bayer, scaled to 0-255 so it compares directly against\n"
             "// Stage::light with no division at draw time.\n"
             "inline constexpr uint8_t BAYER8[64] = {\n")
    flat = (cave.BAYER * 255).round().astype(int).flatten()
    for r in range(8):
        p.append("  " + ", ".join(f"{v:>3}" for v in flat[r * 8:r * 8 + 8]) + ",\n")
    p.append("};\n")
    return "".join(p)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    text = emit()
    (args.out / "constants.h").write_text(text, encoding="utf-8")

    print(f"{len(cave.STAGES)} stages, "
          f"sun at distance {cave.STAGES[-1][1]}")
    for name, start, *_ in cave.STAGES:
        print(f"  {name:<8} from {start:>6}")
    print(f"\nwrote {args.out}\\constants.h")


if __name__ == "__main__":
    main()
