#!/usr/bin/env python3
"""
Export the game's tuning constants from cave.py as a C header.

    python bake_constants.py

Writes firmware/plato/assets/constants.h.

This exists because the same values once lived in both tools/preview.py and the
T-QT sketch, kept in step by a comment asking editors to remember -- and they
drifted within a day. cave.py is the single source of truth; the firmware reads
what this emits and nobody retypes anything.

Colours are converted to RGB565 here rather than on the device, since that is
what the ST7789 wants and the conversion is fixed.
"""

import argparse
from pathlib import Path

import cave
from bake_assets import LABELS

OUT = Path(__file__).parent.parent / "firmware" / "plato" / "assets"


def rgb565(rgb) -> int:
    r, g, b = rgb
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def label_index(greek: str) -> int:
    for i, (_, text) in enumerate(LABELS):
        if text == greek:
            return i
    raise SystemExit(f"stage '{greek}' has no baked label -- add it to "
                     f"LABELS in bake_assets.py")


def emit() -> str:
    p = ["// Generated by tools/bake_constants.py from tools/cave.py.\n"
         "// Do not edit: change cave.py and re-run the baker.\n"
         "#pragma once\n#include <stdint.h>\n#include \"labels.h\"\n\n"
         "// ---- pacing -----------------------------------------------------\n"
         "// Every rate is per SECOND. Distance is measured in cave columns.\n"
         "// Frame-rate independence is verified in the Python model across\n"
         "// 30-144 fps; keep it that way -- per-frame rates put the sun at 25 s\n"
         "// on a 50 fps device and 14 s on a 90 fps one.\n"]

    p.append(f"constexpr float SPEED_START = {cave.SPEED_START:.1f}f;"
             "   // columns/second in the first region\n")
    p.append("// Difficulty steps PER REGION rather than ramping across the whole\n"
             "// run. Under continuous ramps a typical run met 17% of the\n"
             "// narrowing and 8% of the acceleration before it ended -- the\n"
             "// regions were colours, not difficulties. Front-loaded, because\n"
             "// real play ends around region 3.\n"
             "//\n"
             "// A step eases in over STEP_SPAN rather than snapping: instant\n"
             "// would narrow the passage around a player already committed.\n")
    p.append(f"constexpr float STEP_SPAN = {cave.STEP_SPAN}.0f;\n")
    p.append("inline constexpr float REGION_GAP[REGION_COUNT] = {"
             + ", ".join(f"{v:.3f}f" for v in cave.REGION_GAP)
             + "};   // * H\n")
    p.append("inline constexpr float REGION_SPEED[REGION_COUNT] = {"
             + ", ".join(f"{v:.1f}f" for v in cave.REGION_SPEED)
             + "};  // col/s\n\n")

    p.append("// ---- the return -------------------------------------------------\n"
             "// Republic ~516e-517a. The return continues the same per-region\n"
             "// steps past the sun, tighter and faster than any ascent region.\n")
    p.append(f"constexpr float SUN_HOLD      = {cave.SUN_HOLD}.0f;"
             "   // distance held at the sun before turning back\n")
    p.append(f"constexpr float DESCENT_START = {cave.DESCENT_START}.0f;\n")
    p.append(f"constexpr float WIN_DIST      = {cave.WIN_DIST}.0f;"
             "   // reaching this completes the game\n\n")

    p.append("// The closing view: the returning eye cannot see far. Applied AFTER\n"
             "// the rock edge is drawn, so the edge is occluded too -- otherwise\n"
             "// the passage ahead stays readable and the mechanic does nothing.\n"
             "// TUNING RISK: at VIEW_CLOSE 0.55 the clear view at the chains is\n"
             "// ~0.60s against 3.62s at the start. 0.40 gives ~0.82s. Unresolved\n"
             "// until played.\n")
    p.append(f"constexpr float VIEW_CLOSE = {cave.VIEW_CLOSE:.2f}f;"
             "   // fraction of width swallowed\n")
    p.append(f"constexpr float VIEW_DEPTH = {cave.VIEW_DEPTH:.2f}f;"
             "   // dimming at the right edge\n\n")

    p.append("// ---- trail ------------------------------------------------------\n"
             "// Two constraints the firmware must honour or the trail vanishes:\n"
             "//\n"
             "//  1. Draw it as CONNECTED SEGMENTS, not isolated points. A single\n"
             "//     pixel cannot compete with a single-pixel dither -- in a\n"
             "//     50-80% lit field it is just another dither cell.\n"
             "//  2. Flip its polarity on the region's light. Brighter than the\n"
             "//     passage below 128/255, darker above; a trail that only\n"
             "//     brightens is invisible from SELENE onward.\n"
             "//\n"
             "// TWIN_TRAIL draws two strands rather than one: the Phaedrus\n"
             "// chariot's two horses, whichever is being obeyed leading. Set 0\n"
             "// for a single strand.\n")
    p.append(f"constexpr uint8_t TWIN_TRAIL   = {1 if cave.TWIN_TRAIL else 0};\n")
    p.append(f"constexpr float   TRAIL_BASE   = {cave.TRAIL_BASE:.2f}f;"
             "  // px of divergence at the player\n")
    p.append(f"constexpr float   TRAIL_SPREAD = {cave.TRAIL_SPREAD:.2f}f;"
             "  // px added per frame of age\n")
    p.append("constexpr uint8_t TRAIL_LEN    = 40;      // points retained\n\n")

    p.append("// ---- region texture ---------------------------------------------\n"
             "// Three regions name something that behaves, not just something\n"
             "// coloured. Matched on Region::label, so the return gets them too.\n")
    p.append(f"constexpr uint8_t FLICKER_LABEL = LBL_"
             f"{LABELS[label_index(cave.FLICKER_REGION)][0]};"
             "   // firelight is not steady\n")
    p.append(f"constexpr float   FLICKER_DEPTH = {cave.FLICKER_DEPTH:.2f}f;"
             "  // peak swing in light\n")
    p.append(f"constexpr uint8_t STARS_LABEL   = LBL_"
             f"{LABELS[label_index(cave.STARS_REGION)][0]};"
             "   // rock reads as sky by now\n")
    p.append(f"constexpr uint16_t STAR_RARITY  = {cave.STAR_RARITY};"
             "    // 1 in N rock pixels\n")
    p.append("// Stars are placed by WORLD column, not screen column, or they\n"
             "// swim across the rock as the cave scrolls.\n\n")

    p.append("// HYDOR has no special texture. A reflection was built and\n"
             "// rejected; see GAME_DESIGN.\n\n")

    p.append("// ---- physics ----------------------------------------------------\n"
             "// Scaled by panel height H. THRUST replaces gravity while the\n"
             "// button is held; it does not add to it.\n"
             "// UNVALIDATED: these three have never been driven by a human thumb.\n")
    p.append(f"constexpr float GRAVITY = {cave.GRAVITY:.2f}f;   // * H px/s^2\n")
    p.append(f"constexpr float THRUST  = {cave.THRUST:.2f}f;   // * H px/s^2\n")
    p.append(f"constexpr float VY_MAX  = {cave.VY_MAX:.2f}f;   // * H px/s\n\n")

    p.append("// ---- cave shape -------------------------------------------------\n"
             "constexpr float DRIFT_STEP   = 0.42f;   // uniform +/- per column\n"
             "constexpr float DRIFT_CLAMP  = 2.60f;\n"
             "constexpr float DRIFT_DAMP   = 0.94f;\n"
             "constexpr float WALL_MARGIN  = 0.06f;   // * H, beyond gap/2\n"
             "constexpr float PLAYER_X_FRAC = 0.17f;  // * W\n\n")

    p.append("// ---- regions ----------------------------------------------------\n"
             "// Republic 514a-517a ascending, then the return. Each region names\n"
             "// its own light source, which is where its colour comes from. The\n"
             "// return reuses the ascent's names and colours at lower light: the\n"
             "// prisoner coming back from the sun cannot see in the dark.\n"
             "struct Region {\n"
             "  uint8_t  label;    // index into LABELS[] in labels.h\n"
             "  uint32_t from;     // distance at which this region begins\n"
             "  uint8_t  light;    // dither density, 0-255\n"
             "  uint16_t rock;     // RGB565\n"
             "  uint16_t glow;     // RGB565\n"
             "};\n\n")
    p.append(f"constexpr uint8_t REGION_COUNT = {len(cave.REGIONS)};\n")
    p.append(f"constexpr uint8_t ASCENT_COUNT = {len(cave.STAGES)};"
             "   // regions at and past this index are the return\n")
    p.append("inline constexpr Region REGIONS[REGION_COUNT] = {\n")
    for i, (name, start, light, rock, glow) in enumerate(cave.REGIONS):
        phase = "ascent" if i < len(cave.STAGES) else "return"
        # The comma belongs to the label, not to the padding. Formatting the
        # name to a fixed width and then adding a space emitted
        # "{LBL_SKIAI      0, ...}" -- a missing separator, and invalid C.
        lbl = f"LBL_{LABELS[label_index(name)][0]},"
        p.append(f"  {{{lbl:<20}{start:>6}, {round(light * 255):>3}, "
                 f"0x{rgb565(rock):04X}, 0x{rgb565(glow):04X}}},"
                 f"  // {i:>2} {name:<8} {phase}\n")
    p.append("};\n\n")

    p.append("// ---- dither -----------------------------------------------------\n"
             "// 8x8 Bayer, scaled to 0-255 so it compares directly against\n"
             "// Stage::light with no division at draw time.\n"
             "inline constexpr uint8_t BAYER8[64] = {\n")
    flat = (cave.BAYER * 255).round().astype(int).flatten()
    for r in range(8):
        p.append("  " + ", ".join(f"{v:>3}" for v in flat[r * 8:r * 8 + 8]) + ",\n")
    p.append("};\n")
    return "".join(p)


# Module-level constants in cave.py that deliberately do NOT reach the firmware,
# because they are Python-side scaffolding or are folded into the region table at
# bake time. Anything not listed here and not present in the output is reported
# as unbaked -- the default is "must be exported", which is the safe direction.
NOT_BAKED = {
    "W", "H", "PLAYER_X",                      # set by configure(), not fixed
    "LIGHT_FLOOR",                             # already applied to REGIONS
}


def unbaked(header: str):
    """Constants defined in cave.py that never made it into the header.

    This has now caught the same mistake three times -- descent constants, trail
    constants, region-texture constants -- each added to cave.py and silently
    left out of the export. A comment asking future editors to remember is
    exactly what failed before, so check it mechanically instead.
    """
    missing = []
    for name, value in vars(cave).items():
        if not name.isupper() or name.startswith("_"):
            continue
        if not isinstance(value, (int, float, bool)):
            continue
        if name in NOT_BAKED or name in header:
            continue
        missing.append(name)
    return sorted(missing)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    text = emit()
    (args.out / "constants.h").write_text(text, encoding="utf-8")

    gaps = unbaked(text)
    if gaps:
        print(f"\n!! {len(gaps)} constant(s) in cave.py never reach the firmware:")
        for g in gaps:
            print(f"     {g} = {getattr(cave, g)}")
        print("   Add them to emit(), or to NOT_BAKED if that is deliberate.")

    print(f"{len(cave.REGIONS)} regions "
          f"({len(cave.STAGES)} ascending, "
          f"{len(cave.REGIONS) - len(cave.STAGES)} returning), "
          f"win at {cave.WIN_DIST}")
    for i, (name, start, light, *_) in enumerate(cave.REGIONS):
        phase = "ascent" if i < len(cave.STAGES) else "return"
        print(f"  {i:>2}  {name:<8} {phase}  from {start:>6}  "
              f"light {round(light * 255):>3}/255")
    print(f"\nwrote {args.out}\\constants.h")


if __name__ == "__main__":
    main()
