#!/usr/bin/env python3
"""
Export cave.py's constants into web/index.html.

    python bake_web.py

The playable build exists to tune the three physics constants and VIEW_CLOSE
against a real thumb, which only works if it is running the *same* numbers as
the model and the firmware. So they are generated here, not retyped -- the same
reason bake_constants.py exists, and the same mistake it has caught three times.

Rewrites the block between the GENERATED markers in web/index.html and leaves
the hand-written game code alone.
"""

import argparse
import base64
import re
from pathlib import Path

import cave

BEGIN = "// ---- BEGIN GENERATED by tools/bake_web.py -- do not edit by hand ----"
END = "// ---- END GENERATED ----"


def js_regions():
    rows = []
    for i, (name, frm, light, rock, glow) in enumerate(cave.REGIONS):
        phase = "ascent" if i < len(cave.STAGES) else "return"
        rows.append(
            f'  {{name:"{name}",label:"{name}",from:{frm},'
            f'light:{round(light * 255)},'
            f'rock:[{rock[0]},{rock[1]},{rock[2]}],'
            f'glow:[{glow[0]},{glow[1]},{glow[2]}]}},'
            f'  // {i:>2} {phase}')
    return "const REGIONS=[\n" + "\n".join(rows) + "\n];"


def bust():
    """The title bust, out of the committed header rather than the photograph.

    bake_assets.py makes bust.h from image/plato.png, which is *not* in the
    repository -- so reading the photo here would make this script unrunnable on
    a fresh clone, and it is the one baker CI depends on. The header is the
    committed artifact, so it is the honest source for a second consumer.

    Parsed without a regex: the file is machine-written and the shape is fixed.
    """
    h = Path(__file__).parent.parent / "firmware" / "plato" / "assets" / "bust.h"
    if not h.exists():
        print(f"  !! {h.name} missing -- title screen will have no bust")
        return 0, 0, ""
    text = h.read_text()
    dims = {}
    for key in ("BUST_W", "BUST_H"):
        line = next(l for l in text.splitlines() if l.startswith(f"#define {key}"))
        dims[key] = int(line.split()[2])
    body = text[text.index("BUST_BITS"):]
    body = body[body.index("{") + 1:body.index("}")]
    data = bytes(int(t, 16) for t in
                 (t.strip() for t in body.split(",")) if t.startswith("0x"))
    stride = (dims["BUST_W"] + 7) // 8
    want = stride * dims["BUST_H"]
    if len(data) != want:
        raise SystemExit(f"bust.h: {len(data)} bytes, expected {want} "
                         f"({stride}/row x {dims['BUST_H']} rows)")
    print(f"  bust {dims['BUST_W']}x{dims['BUST_H']}, {len(data)} bytes "
          f"-> {len(base64.b64encode(data))} b64 chars")
    return dims["BUST_W"], dims["BUST_H"], base64.b64encode(data).decode()


def emit():
    b = (cave.BAYER * 255).round().astype(int).flatten()
    bw, bh, b64 = bust()
    return "\n".join([
        BEGIN,
        f"const W={cave.W},H={cave.H};",
        js_regions(),
        f"const SPEED_START={cave.SPEED_START},STEP_SPAN={cave.STEP_SPAN};",
        "const REGION_GAP=[" + ",".join(str(v) for v in cave.REGION_GAP) + "];",
        "const REGION_SPEED=[" + ",".join(str(v) for v in cave.REGION_SPEED) + "];",
        f"const DESCENT_START={cave.DESCENT_START},WIN_DIST={cave.WIN_DIST};",
        f"const GRAVITY={cave.GRAVITY},THRUST={cave.THRUST},VY_MAX={cave.VY_MAX};",
        "const DRIFT_STEP=0.42,DRIFT_CLAMP=2.6,DRIFT_DAMP=0.94;",
        "const WALL_MARGIN=0.06,PLAYER_X_FRAC=0.17;",
        f"const TWIN_TRAIL={1 if cave.TWIN_TRAIL else 0},"
        f"TRAIL_BASE={cave.TRAIL_BASE},TRAIL_SPREAD={cave.TRAIL_SPREAD},"
        f"TRAIL_LEN=40;",
        f"const VIEW_CLOSE={cave.VIEW_CLOSE},VIEW_DEPTH={cave.VIEW_DEPTH};",
        f'const FLICKER_LABEL="{cave.FLICKER_REGION}",'
        f"FLICKER_DEPTH={cave.FLICKER_DEPTH},"
        f'STARS_LABEL="{cave.STARS_REGION}",STAR_RARITY={cave.STAR_RARITY};',
        f"const ASCENT_COUNT={len(cave.STAGES)};",
        "const BAYER=[" + ",".join(str(v) for v in b) + "];",
        f"const BUST_W={bw},BUST_H={bh};",
        f'const BUST_B64="{b64}";',
        END,
    ])


def main():
    here = Path(__file__).parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--page", type=Path, default=here.parent / "web" / "index.html")
    args = ap.parse_args()

    html = args.page.read_text(encoding="utf-8")
    if BEGIN not in html or END not in html:
        raise SystemExit(f"markers not found in {args.page}")
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), emit(), html,
                 flags=re.S)
    args.page.write_text(new, encoding="utf-8")

    kb = args.page.stat().st_size / 1024
    print(f"{len(cave.REGIONS)} regions, win at {cave.WIN_DIST}")
    print(f"physics: GRAVITY {cave.GRAVITY}  THRUST {cave.THRUST}  "
          f"VY_MAX {cave.VY_MAX}   VIEW_CLOSE {cave.VIEW_CLOSE}")
    print(f"wrote {args.page}  ({kb:.0f} KB, self-contained)")


if __name__ == "__main__":
    main()
