#!/usr/bin/env python3
"""
Bake images and Greek text into 1-bit C headers for the firmware.

    python bake_assets.py

Writes firmware/plato/assets/bust.h and labels.h.

Two things must be baked rather than computed on the device:

  * The title bust. Bayer dithering has to happen at the size it will be shown --
    dithering at one size and scaling destroys the pattern, because nearest
    neighbour drops half the cells and the face turns to gravel.
  * The Greek text. Baking ΣΚΙΑΙ..ΗΛΙΟΣ as bitmaps avoids carrying a
    Greek-capable font in flash, which would cost far more than the ~1 KB these do.

Bitmap format is 1bpp, MSB first, each row padded to a whole byte -- the layout
LovyanGFX's drawBitmap() expects.
"""

import argparse
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

import image_treatments

FONT = "C:/Windows/Fonts/consola.ttf"
OUT = Path(__file__).parent.parent / "firmware" / "plato" / "assets"

# 8x8 Bayer, matching tools/cave.py.
BAYER = np.array([
    [0, 32, 8, 40, 2, 34, 10, 42], [48, 16, 56, 24, 50, 18, 58, 26],
    [12, 44, 4, 36, 14, 46, 6, 38], [60, 28, 52, 20, 62, 30, 54, 22],
    [3, 35, 11, 43, 1, 33, 9, 41], [51, 19, 59, 27, 49, 17, 57, 25],
    [15, 47, 7, 39, 13, 45, 5, 37], [63, 31, 55, 23, 61, 29, 53, 21],
], np.float32) / 64.0

# Ordered, and the single source of truth for label identity. bake_constants.py
# imports this to emit stage entries that index into it, so the two headers
# cannot disagree about what LBL_HELIOS means.
LABELS = [
    ("SKIAI",         "ΣΚΙΑΙ"),        # stage 1 -- shadows
    ("PYR",           "ΠΥΡ"),          # stage 2 -- the fire
    ("EIDOLA",        "ΕΙΔΩΛΑ"),       # stage 3 -- carried images
    ("HYDOR",         "ΥΔΩΡ"),         # stage 4 -- water
    ("ASTRA",         "ΑΣΤΡΑ"),        # stage 5 -- the stars
    ("SELENE",        "ΣΕΛΗΝΗ"),       # stage 6 -- the moon
    ("HELIOS",        "ΗΛΙΟΣ"),        # stage 7 -- the sun
    ("HOI_LYTHENTES", "ΟΙ ΛΥΘΕΝΤΕΣ"),  # high-score header, "those who were released"
    ("DESMOTES",      "ΔΕΣΜΩΤΗΣ"),     # game over -- "prisoner"
    ("LELYTAI",       "ΛΕΛΥΤΑΙ"),      # score table: a completed run, "has been freed"
    ("KATEBEN",       "ΚΑΤΕΒΗΝ"),      # victory -- the Republic's first word, "I went down"
    ("PERIAGOGE",     "ΠΕΡΙΑΓΩΓΗ"),    # the turn at the sun -- Republic 518d
    ("TYPHLOS",       "ΤΥΦΛΟΣ"),       # died on the return -- "blind", 516e
]

# Only Greek needs baking. LovyanGFX ships Latin fonts, so the English on these
# screens costs nothing.

# Uppercase Greek, for arcade initials entry. Final sigma is omitted: it never
# begins a word and would only be a confusing extra step on the dial.
ALPHABET = "ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ"


def pack_1bit(mask: np.ndarray) -> bytes:
    """Bool array (h, w) -> 1bpp MSB-first, rows padded to whole bytes."""
    h, w = mask.shape
    stride = (w + 7) // 8
    out = bytearray(h * stride)
    for y in range(h):
        row = mask[y]
        for x in range(w):
            if row[x]:
                out[y * stride + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(out)


def c_array(name: str, data: bytes, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + per_line])
        lines.append("    " + chunk + ",")
    return (f"inline constexpr uint8_t {name}[] = {{\n"
            + "\n".join(lines) + "\n};\n")


def render_text(text: str, size: int) -> np.ndarray:
    """Rasterise to a tight 1-bit mask, cropped to its ink."""
    font = ImageFont.truetype(FONT, size)
    probe = Image.new("L", (len(text) * size * 2 + 8, size * 3), 0)
    ImageDraw.Draw(probe).text((4, 4), text, font=font, fill=255)
    box = probe.getbbox()
    if box is None:
        raise SystemExit(f"'{text}' rendered blank -- font lacks these glyphs?")
    return np.asarray(probe.crop(box), np.uint8) > 128


def bake_labels(size: int) -> str:
    parts = [
        "// Generated by tools/bake_assets.py -- do not edit.\n"
        "// 1bpp, MSB first, rows padded to whole bytes (LovyanGFX drawBitmap).\n"
        "#pragma once\n#include <stdint.h>\n\n"
        "struct Bitmap1 { uint8_t w, h; const uint8_t* bits; };\n\n"
    ]
    ids = []
    for ident, text in LABELS:
        mask = render_text(text, size)
        h, w = mask.shape
        parts.append(f"// {text}  ({w}x{h})\n")
        parts.append(c_array(f"LBL_{ident}_BITS", pack_1bit(mask)))
        ids.append((ident, w, h))
        print(f"  label {text:<14} {w:>3} x {h:<3}  "
              f"{len(pack_1bit(mask)):>4} bytes")

    parts.append("\nenum LabelId : uint8_t {\n")
    parts += [f"  LBL_{i} = {n},\n" for n, (i, _, _) in enumerate(ids)]
    parts.append("  LABEL_COUNT\n};\n\n")
    parts.append("inline constexpr Bitmap1 LABELS[LABEL_COUNT] = {\n")
    parts += [f"  {{{w:>3}, {h:>3}, LBL_{i}_BITS}},\n" for i, w, h in ids]
    parts.append("};\n")
    return "".join(parts)


def bake_alphabet(size: int) -> str:
    """Fixed-cell glyph strip, so the firmware can index by letter number."""
    glyphs = [render_text(c, size) for c in ALPHABET]
    cw = max(g.shape[1] for g in glyphs)
    ch = max(g.shape[0] for g in glyphs)
    cell = np.zeros((len(glyphs) * ch, cw), bool)
    for i, g in enumerate(glyphs):                    # centre each in its cell
        h, w = g.shape
        y0, x0 = i * ch + (ch - h) // 2, (cw - w) // 2
        cell[y0:y0 + h, x0:x0 + w] = g
    print(f"  alphabet {len(glyphs)} glyphs, cell {cw}x{ch}, "
          f"{len(pack_1bit(cell))} bytes")
    return (f"\n// Uppercase Greek for initials entry: {len(glyphs)} glyphs,\n"
            f"// stacked vertically in fixed {cw}x{ch} cells. Glyph n starts at\n"
            f"// row n*{ch}. Final sigma is deliberately absent.\n"
            f"#define GREEK_GLYPH_COUNT {len(glyphs)}\n"
            f"#define GREEK_GLYPH_W {cw}\n#define GREEK_GLYPH_H {ch}\n"
            + c_array("GREEK_GLYPHS", pack_1bit(cell)))


def bake_bust(path: Path, size: int) -> str:
    g = image_treatments.prepare(path, 1.0, crop=True, size=size)
    tile = np.tile(BAYER, (size // 8 + 1, size // 8 + 1))[:size, :size]
    mask = g > tile
    data = pack_1bit(mask)
    print(f"  bust {size}x{size}, {len(data)} bytes "
          f"({mask.mean() * 100:.0f}% lit)")
    return ("// Generated by tools/bake_assets.py -- do not edit.\n"
            f"// Title bust, Bayer-dithered AT {size}px. Do not rescale on the\n"
            "// device: resampling a dither destroys the pattern.\n"
            "#pragma once\n#include <stdint.h>\n\n"
            f"#define BUST_W {size}\n#define BUST_H {size}\n"
            + c_array("BUST_BITS", data))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", type=Path,
                    default=Path(__file__).parent.parent / "image" / "plato.png")
    ap.add_argument("--bust-size", type=int, default=118)
    ap.add_argument("--label-size", type=int, default=11)
    # Larger than the labels on purpose: during initials entry the selected
    # letter is the subject of the screen, not an annotation on it, and Greek
    # has glyphs (Ξ, Ψ, Ω) that simply do not survive a 6 px cell.
    ap.add_argument("--alphabet-size", type=int, default=19)
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    print("baking labels:")
    labels = bake_labels(args.label_size) + bake_alphabet(args.alphabet_size)
    (args.out / "labels.h").write_text(labels, encoding="utf-8")

    print("baking bust:")
    (args.out / "bust.h").write_text(
        bake_bust(args.image, args.bust_size), encoding="utf-8")

    total = sum((args.out / f).stat().st_size for f in ("labels.h", "bust.h"))
    print(f"\nwrote {args.out}\\labels.h and bust.h  ({total // 1024} KB of source)")


if __name__ == "__main__":
    main()
